NATIONAL_ID_TYPE_CODES = (
    ('00010', 'Belgium Enterprise Number'),
    ('00011', 'Belgium Branch Unit Number'),
    ('00012', 'UK CRO Number'),
    ('00013', 'IRELAND CRO Number'),
    ('00014', 'France SIREN Number'),
    ('00015', 'France Chamber of Commerce Number'),
    ('00016', 'Monte Carlo Siren Number'),
    ('00017', 'France SIRET Number'),
    ('00018', 'Europe Standard VAT Number'),
    ('00019', 'Netherlands Trade Register Number'),
    ('00020', 'Germany Registration Number'),
    ('00021', 'Italy Chamber of Commerce Number'),
    ('00022', 'TAIWAN BUSINESS REGISTRATION NUMBER'),
    ('00024', 'Spain Fiscal Code'),
    ('00025', 'ANDORRA FISCAL CODE'),
    ('00026', 'PORTUGAL FISCAL CODE'),
    ('00030', 'CUSIP NUMBER'),
    ('00031', 'AUSTRALIA COMPANY NUMBER'),
    ('00032', 'SINGAPORE REGISTRATION FILE NUMBER'),
    ('00033', 'HONG KONG CO REGISTRY COMPANY ID NUMBER'),
    ('00034', 'CINS NUMBER'),
    ('00035', 'Panamanian Sole Commercial Registry Nbr'),
    ('00035', 'Panamanian Sole Commercial Registry Nbr'),
    ('00036', 'Portugal Chamber of Commerce Number'),
    ('00040', 'MEXICO IVA'),
    ('00042', 'Netherlands Branch Unit Number'),
    ('00043', 'Netherlands Legal Entity and Partnership Information Number'),
    ('00045', 'ISRAEL REGISTRATION NUMBER'),
    ('00050', 'ISRAEL VAT NUMBER'),
    ('00055', 'LIECHTENSTEIN REGISTRATION NUMBER'),
    ('00060', 'ITALY FISCAL CODE'),
    ('00065', 'DENMARK REGISTRATION NUMBER'),
    ('00070', 'AUSTRIA TRADE REGISTER NUMBER'),
    ('00075', 'ZIMBABWE ORGANIZATION REGISTRATION NBR'),
    ('00080', 'ZIMBABWE INDIVIDUAL REGISTRATION NBR'),
    ('00090', 'GUATEMALAN SOLE COMMERCIAL REGISTRY NBR'),
    ('00095', 'COLOMBIAN REGISTRY OF FISCAL INFO'),
    ('00099', 'Japan Corporate Number'),
    ('00100', 'TOKYO SHOKO RESEARCH BUSINESS IDENTIFIER'),
    ('00101', 'Japan Stock Exchange Number'),
    ('00102', 'Local Government Registration Number'),
    ('00103', 'Local Government Tax Registration Number'),
    ('00104', 'Local Government Chamber of Commerce Number'),
    ('00105', 'Local Government Gazette Number'),
    ('00106', 'SWEDEN REGISTRATION NUMBER'),
    ('00107', 'FINNISH REGISTRATION NUMBER'),
    ('00108', 'COSTA RICAN JUDICIAL NUMBER'),
    ('00109', 'EL SALVADORAN PATRON'),
    ('00110', 'HUNGARIAN TAX IDENTIFIER'),
    ('00111', 'SWEDEN BRANCH NUMBER'),
    ('00112', 'JAMAICAN TAX IDENTIFICATION NUMBER'),
    ('00113', 'TRINIDADIAN TAX IDENTIFICATION NUMBER'),
    ('00115', 'DOMINICAN REPUBLIC NATIONAL COMMERCIAL REGISTRY NUMBER'),
    ('00119', 'PERUVIAN SOLE COMMERCIAL REGISTRY NUMBER'),
    ('00120', 'HUNGARIAN REGISTRATION NUMBER'),
    ('00122', 'East Timor Tax Identification Number'),
    ('00125', 'VENEZUELAN NATIONAL TRIBUTARY ID NUMBER'),
    ('00127', 'NICARAGUAN SOLE COMMERCIAL REGISTRY NBR'),
    ('00130', 'POLISH VALUE ADDED TAX NUMBER (NIP)'),
    ('00135', 'COSTA RICAN TAX REGISTRATION NUMBER'),
    ('00140', 'POLISH NATIONAL OFFICIAL REGISTER NUMBER (REGON)'),
    ('00142', 'POLISH NATIONAL COURT COUNCIL NUMBER'),
    ('00143', 'POLISH LICENSE NUMBER'),
    ('00145', 'COLOMBIAN NATIONAL TRUBUTARY ID NUMBER'),
    ('00155', 'EL SALVADORAN NATIONAL TRIBUTARY ID NBR'),
    ('00165', 'BOLIVIAN SOLE COMMERCIAL REGISTRY NUMBER'),
    ('00175', 'ECUADORIAN SOLE COMMERCIAL REGISTRY NBR'),
    ('00185', 'SOLE COMMERCIAL REGISTRY NBR UNK CTRY'),
    ('00195', 'NATIONAL TRIBUTARY ID NUMBER UNK COUNTRY'),
    ('00200', 'ARGENTINIAN UNIQUE TAX ID KEY'),
    ('00210', 'PARAGUAYAN UNIQUE TAX REGISTRATION'),
    ('00211', 'BRAZILIAN STATE REGISTRY NUMBER'),
    ('00212', 'BRAZILIAN MUNICIPAL REGISTRY NUMBER'),
    ('00220', 'URUGUAYAN UNIQUE TAX REGISTRATION'),
    ('00230', 'MEXICAN FEDERAL TAX REGISTRATION'),
    ('00240', 'CHILEAN UNIQUE TAX ID'),
    ('00250', 'VENEZUELAN REGISTRY OF FISCAL INFO'),
    ('00260', 'Brazil CNPJ Number - National Registry of Legal Entities'),
    ('00270', 'Norwegian Government Organization Number'),
    ('00270', 'NORWEGIAN GOVERNMENT ORGANIZATION NUMBER'),
    ('00281', 'Hong Kong Business Registration Number'),
    ('00282', 'Macao Commercial Registry Company ID Nbr'),
    ('00283', 'Macao Commercial Registry Business Registration Nbr'),
    ('00284', 'S. Korean State Commercial Registry Business Registration Number'),
    ('00285', 'S. Korean Trade Association Export/Import Registration Number'),
    ('00286', 'Czech Republic ICO Number'),
    ('00290', 'Czech Republic VAT Number'),
    ('00292', 'Czech Republic Group VAT Number'),
    ('00293', 'Czech Republic Tax Registration Number'),
    ('00300', 'Bangladesh Company Incorporation Number'),
    ('00301', 'Brunei Registration Number'),
    ('00302', 'India Company Incorporation Number'),
    ('00303', 'Indonesia Legalization Number'),
    ('00304', 'Indonesia President Decree Number'),
    ('00305', 'Malaysia Company Registration Number'),
    ('00306', 'Malaysia Business Registration Number'),
    ('00307', 'Nepal Company Incorporation Number'),
    ('00320', 'HUNGARIAN VAT NUMBER'),
    ('00322', 'Australia Business Registration Number'),
    ('00330', 'Philippinies Securities & Exchange Commission Number'),
    ('00335', 'India Society Registration Number'),
    ('00340', 'India Trade Registration Number'),
    ('00342', 'India Goods & Services (GST) ID'),
    ('00345', 'Pakistan Securites & Exchange Commission Number'),
    ('00350', 'Thailand Commercial Registration Number'),
    ('00355', 'Thailand Securities & Exchange Commission Number'),
    ('00360', 'Austria Association Registration Number'),
    ('00362', 'Monaco Trade & Industry Registration Number'),
    ('00365', 'Hungary KSH Number'),
    ('00400', 'Value Added Tax Number (IN)'),
    ('00519', 'Value Added Tax Number (AE)'),
    ('00520', 'Value Added Tax Number (SA)'),
    ('00521', 'Denmark CVR Number'),
    ('00522', 'United Arab Emirates Registration Number'),
    ('00523', 'Bahrain Registration Number'),
    ('00524', 'Iraq Registration Number'),
    ('00525', 'Iran Registration Number'),
    ('00526', 'Jordan Registration Number'),
    ('00527', 'Kuwait Registration Number'),
    ('00528', 'Lebanon Registration Number'),
    ('00529', 'Oman Registration Number'),
    ('00530', 'Qatar Registration Number'),
    ('00531', 'Saudi Arabia Registration Number'),
    ('00532', 'Syria Registration Number'),
    ('00533', 'Yemen Registration Number'),
    ('00536', 'Iran Chamber Of Commerce Number'),
    ('00537', 'Jordan Chamber Of Commerce Number'),
    ('00538', 'Kuwait Chamber Of Commerce Number'),
    ('00539', 'Lebanon Chamber Of Commerce Number'),
    ('00540', 'Oman Chamber Of Commerce Number'),
    ('00541', 'Qatar Chamber Of Commerce Number'),
    ('00542', 'Saudi Arabia Chamber Of Commerce Number'),
    ('00543', 'Syria Chamber Of Commerce Number'),
    ('00544', 'Yemen Chamber Of Commerce Number'),
    ('00545', 'Angola Registration Number'),
    ('00546', 'Burkino Faso Registration Number'),
    ('00547', 'Burundi Registration Number'),
    ('00548', 'Benin Registration Number'),
    ('00549', 'Central African Republic Registration Number'),
    ('00550', 'Congo Registration Number'),
    ('00551', 'Ivory Coast Registration Number'),
    ('00552', 'Cameroon Registration Number'),
    ('00553', 'Cape Verde Registration Number'),
    ('00554', 'Djibouti Registration Number'),
    ('00555', 'Algeria Registration Number'),
    ('00556', 'Egypt Registration Number'),
    ('00557', 'Eritrea Registration Number'),
    ('00558', 'Ethiopia Registration Number'),
    ('00559', 'Falkland Islands Registration Number'),
    ('00560', 'Gabon Registration Number'),
    ('00561', 'Ghana Registration Number'),
    ('00562', 'Gambia Registration Number'),
    ('00563', 'Guinea Registration Number'),
    ('00564', 'Equatorial Guinea Registration Number'),
    ('00565', 'Guinea-Bissau Registration Number'),
    ('00566', 'Kenya Registration Number'),
    ('00567', 'Comoros Registration Number'),
    ('00568', 'Liberia Registration Number'),
    ('00569', 'Morocco Registration Number'),
    ('00570', 'Madagascar Registration Number'),
    ('00571', 'Mali Registration Number'),
    ('00572', 'Mauritania Registration Number'),
    ('00573', 'Mauritius Registration Number'),
    ('00574', 'Malawi Registration Number'),
    ('00575', 'Mozambique Registration Number'),
    ('00576', 'Niger Registration Number'),
    ('00577', 'Nigeria Registration Number'),
    ('00578', 'Rwanda Registration Number'),
    ('00579', 'Seychelles Registration Number'),
    ('00580', 'Sudan Registration Number'),
    ('00581', 'St Helena Registration Number'),
    ('00582', 'Sierra Leone Registration Number'),
    ('00583', 'Senegal Registration Number'),
    ('00584', 'Somalia Registration Number'),
    ('00585', 'Chad Registration Number'),
    ('00586', 'Togo Registration Number'),
    ('00587', 'Tanzania Registration Number'),
    ('00588', 'Uganda Registration Number'),
    ('00589', 'Zambia Registration Number'),
    ('00590', 'Ivory Coast Chamber Of Commerce Number'),
    ('00591', 'Cameroon Chamber Of Commerce Number'),
    ('00592', 'Algeria Chamber Of Commerce Number'),
    ('00593', 'Egypt Chamber Of Commerce Number'),
    ('00594', 'Gabon Chamber Of Commerce Number'),
    ('00595', 'Morocco Chamber Of Commerce Number'),
    ('00596', 'Seychelles Chamber Of Commerce Number'),
    ('00597', 'Senegal Chamber Of Commerce Number'),
    ('00720', 'Swiss Uniform Identification Number (UID)'),
    ('00726', 'Czech Republic Auditor Registration Number'),
    ('00727', 'Czech Republic Trade License Register Number'),
    ('00728', 'Czech Republic Chamber of Bailiffs Number'),
    ('00730', 'Slovakia Court Number of Registration'),
    ('00735', 'Slovakia Tax Registration Number'),
    ('00740', 'Slovakia  IČO  Number'),
    ('00745', 'Slovak VAT Number'),
    ('00748', 'Slovakia Group VAT Number'),
    ('00750', 'Slovakia Registration Number'),
    ('00753', 'Tax Identification Number (IN)'),
    ('00754', 'Economic development board number (IN)'),
    ('00755', 'Securities exchange commission number (IN)'),
    ('00756', 'Ministry of education number (IN)'),
    ('00757', "Provincial people's committee number (IN)"),
    ('00758', 'Ministry of planning and investment number (IN)'),
    ('00759', 'State plan committee number (IN)'),
    ('00760', 'Department of commercial registration number (IN)'),
    ('00761', 'Law society number (IN)'),
)

LEGAL_STATUS_CODES = (
    ('003', 'Corporation'),
    ('008', 'Joint Venture'),
    ('012', 'Partnership Of Unknown Type'),
    ('013', 'Proprietorship'),
    ('050', 'Government Body'),
    ('100', 'Cooperative'),
    ('101', 'Non Profit Organization'),
    ('118', 'Local Government Body'),
    ('120', 'Foreign Company'),
    ('009', 'Master Limited Partnership'),
    ('010', 'General Partnership'),
    ('011', 'Limited Partnership'),
    ('014', 'Limited Liability'),
    ('015', 'Friendly Society'),
    ('030', 'Trust'),
    ('070', 'Crown Corporation'),
    ('080', 'Institution'),
    ('090', 'Estate'),
    ('099', 'Industry Cooperative'),
    ('102', 'Private Limited Company'),
    ('103', 'Partnership Partially Limited By Shares'),
    ('104', 'Temporary Association'),
    ('105', 'Registered Proprietorship'),
    ('106', 'Limited Partnership With Shares'),
    ('107', 'Unregistered Proprietorship'),
    ('108', 'Community Of Goods'),
    ('109', 'Reciprocal Guarantee Company'),
    ('110', 'Cooperative Society With Ltd Liability'),
    ('111', 'Civil Company'),
    ('112', 'De Facto Partnership'),
    ('113', 'Foundation'),
    ('114', 'Association'),
    ('115', 'Public Company'),
    ('116', 'Civil Law Partnership'),
    ('117', 'Incorporated By Act Of Parliament'),
    ('119', 'Private Unlimited Company'),
    ('121', 'Private Company Limited By Guarantee'),
    ('122', 'Civil Partnership'),
    ('125', 'Public Limited Company'),
    ('126', 'Registered Partnership'),
    ('127', 'Society'),
    ('128', 'Government Owned Company'),
    ('129', 'Government Institute'),
    ('130', 'Public Institute'),
    ('131', 'Plant'),
    ('132', 'Hotel'),
    ('133', 'Division'),
    ('140', 'Joint Shipping Company'),
    ('142', 'Limited Liability Corporation'),
    ('143', 'Branch'),
    ('144', 'Concern Address'),
    ('145', 'Insurance Company'),
    ('146', 'Private Foundation'),
    ('147', 'County Institution'),
    ('148', 'Municipal Institution'),
    ('149', 'Vestry'),
    ('150', 'Public Undertaking'),
    ('151', 'Faeroese Company'),
    ('152', 'Greenland Limited'),
    ('153', 'Greenland Private Limited'),
    ('154', 'Sole Proprietorship'),
    ('155', 'Sole Proprietorship Or Partnership'),
    ('160', 'Unregistered Partnership'),
    ('161', 'Civil Association'),
    ('162', 'Association In Participation'),
    ('163', 'Mutual Insurance Association'),
    ('164', 'Stock Company With Variable Capital'),
    ('166', 'Cooperative Production Society'),
    ('167', 'Joint Stock Company'),
    ('168', 'Ltd Responsibility Cooperative Society'),
    ('169', 'National Credit Society'),
    ('170', 'Offene Erwerbsgesellschaft'),
    ('171', 'Ltd Liability Company With Variable Cap'),
    ('180', 'Kommandit Erwerbsgesellschaft'),
    ('185', 'Public Credit Institution'),
    ('186', 'Working Group'),
    ('190', 'Union'),
    ('200', 'Personal Partnership'),
    ('210', 'Real Estate Partnership'),
    ('220', 'Agricultural Collective Interest Company'),
    ('230', 'Defacto Business Organization'),
    ('240', 'Government/Municipal Establishment'),
    ('250', 'Housing Company'),
    ('260', 'Voluntary Association'),
    ('270', 'Mortgage Association'),
    ('280', 'Cooperative Society'),
    ('290', 'Cooperative Bank'),
    ('300', 'Savings Bank'),
    ('301', 'Small Individual Business'),
    ('310', 'Economic Association'),
    ('320', 'Insurance Limited Company'),
    ('330', 'Government Authority'),
    ('340', 'Group'),
    ('350', 'Housing Cooperative Society'),
    ('360', 'Mutual Assistance Business Organization'),
    ('370', 'Provident Business Organization'),
    ('380', 'Limited Company'),
    ('390', 'Simple Partnership'),
    ('400', 'Mixed Company'),
    ('410', 'Commercial Collective Company'),
    ('420', 'Commercial Company'),
    ('430', 'Representative Office'),
    ('440', 'Bank'),
    ('450', 'Industry And Equity Company'),
    ('451', 'Trading Society'),
    ('452', 'Government Institution'),
    ('460', 'Open Stock Corporation'),
    ('470', 'Trusteeship'),
    ('480', 'Private Business'),
    ('490', 'Decentralized Public Organization'),
    ('500', 'Stock Company'),
    ('502', "Tenant Owner'S Society"),
    ('510', 'Civil Society'),
    ('520', 'Society For Capitalization Of Savings'),
    ('530', 'Limited Cooperative Company'),
    ('540', 'Mutual Insurance Society'),
    ('550', 'Simple Limited Partnership'),
    ('560', 'Named Collective Company'),
    ('570', 'Non Profit Association'),
    ('580', 'Corporation With Variable Capital'),
    ('590', 'Joint Corporation'),
    ('600', 'Consortium'),
    ('610', 'Personal Firm'),
    ('620', 'Corporation With Authorized Capital'),
    ('630', 'Corporation With Open Capital'),
    ('640', 'Bank For Capitalization Of Savings'),
    ('650', 'Closed Stock Corporation'),
    ('660', 'Commercial And Industrial Corporation'),
    ('670', 'Commercial Corporation'),
    ('680', 'Industrial Corporation'),
    ('690', 'Financial Institution'),
    ('700', 'Contract Mining Company'),
    ('710', 'Contracting Company'),
    ('720', 'Non Profit International Organization'),
    ('730', 'International Organization'),
    ('740', 'Ltd Co Auth Capital-Regd Co Open Cap'),
    ('750', 'Organization'),
    ('755', 'Unlimited Company'),
    ('760', "Farmer'S Association"),
    ('770', "Economic Assoc/Tenant Owners' Society"),
    ('780', 'Mining Company'),
    ('790', 'Shipping Company'),
    ('800', 'Simple Company'),
    ('810', 'Private Firm'),
    ('820', 'Family Foundation'),
    ('830', 'County'),
    ('840', 'County Association'),
    ('850', 'County Council'),
    ('860', 'Regional Social Insurance Office'),
    ('870', 'Unit Within The Swedish Church'),
    ('880', 'Public Corporation/Institution'),
    ('881', 'Statutory Body'),
    ('890', 'Mortgage/Security Association'),
    ('891', 'Government Agency'),
    ('892', 'Mutual Company'),
    ('893', 'Special Corporation'),
    ('894', 'Central Bank For Agriculture & Forestry'),
    ('895', 'Austrian Legal Entity'),
    ('896', 'Establishment'),
    ('900', 'Supporting Association'),
    ('905', 'Administration'),
    ('910', 'Unemployment Office'),
    ('915', 'Liaison Office'),
    ('920', 'Foreign Legal Person'),
    ('925', 'Cooperative Union With Guaranteed Liab'),
    ('930', 'Swedish Legal Person'),
    ('935', 'Cooperative Union With Limited Liability'),
    ('940', 'Unlimited Partnership'),
    ('945', 'Cooperative Society With Unlimited Liab'),
    ('950', 'Foreign Branch'),
    ('955', 'Cooperative Society With Guaranteed Liab'),
    ('960', 'Incorporated Foundation'),
    ('965', 'Business Not Formally Registered'),
    ('970', 'Incorporated Non Profit Association'),
    ('971', 'State Owned Enterprise'),
    ('972', 'Free Trd. Zone Entp. Proc. Prvd. Smpl.'),
    ('973', 'Limited Holding Company'),
    ('974', 'Govt. Dept. Or Non-Profit Organization'),
    ('975', 'Government Department'),
    ('976', 'Collectively Owned Enterprise'),
    ('977', 'Domestic And Foreign Joint Venture'),
    ('978', 'Domestic And Foreign Cooperative Venture'),
    ('980', 'Educational Foundation'),
    ('985', 'Unlimited Company Ltd. Liab. Shareholder'),
    ('990', 'Medical Corporation'),
    ('991', 'Private Limited Liability Company'),
    ('992', 'Public Limited Liability Company'),
    ('993', 'Exempt Limited Liability Company'),
    ('994', 'Deemed Public Limited Company'),
    ('995', 'Private Company Limited By Shares'),
    ('999', 'Securities Fund'),
)
