version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  rebase-strategy: disabled
  ignore:
      - dependency-name: notifications-python-client
        versions:
        - ">= 6.2.1"