version: "2"
services:
  api:
    build:
      context: .
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://postgres:5432 -wait tcp://redis:6379 -timeout 120s
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: /app/start_docker.sh

  celery:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://postgres:5432 -wait tcp://redis:6379 -timeout 180s
    env_file: .env
    command: watchmedo auto-restart -d . -R -p '*.py' -- celery -A worker config -l info -Q celery -B

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=dnb-service
      - POSTGRES_PASSWORD=dnbservice

  redis:
    image: redis:7.2.4
    restart: always
