version: '2'
services:

  api:
    build:
      context: .
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://postgres:5432 -wait tcp://redis:6379 -timeout 120s
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: /app/start_docker.sh

  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=dnb-service
      - POSTGRES_PASSWORD=dnbservice

  redis:
    image: redis:3.2
    restart: always
