# Generated by Django 2.1.7 on 2019-04-03 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_updated_source', models.PositiveIntegerField(choices=[(2, 'File'), (1, 'API')])),
                ('duns_number', models.CharField(db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid', message='Field should contain 9 numbers only', regex='^\\d{9}$')], verbose_name='Duns number')),
                ('business_name', models.CharField(max_length=90, verbose_name='Business name')),
                ('secondary_name', models.CharField(blank=True, max_length=90, null=True, verbose_name='Secondary name')),
                ('street_address', models.CharField(max_length=64, verbose_name='Street address')),
                ('street_address2', models.CharField(max_length=64, verbose_name='Street address 2')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('country_name', models.CharField(max_length=20, verbose_name='Country name')),
                ('country_code', models.CharField(help_text='3 digit ISO country code', max_length=3, verbose_name='Country code')),
                ('postal_code', models.CharField(max_length=9, verbose_name='Postal code')),
                ('national_id_number', models.CharField(max_length=16, verbose_name='National ID number')),
                ('national_id_code_type', models.CharField(max_length=5, verbose_name='National ID code type')),
                ('line_of_business', models.CharField(max_length=41, verbose_name='Line of business')),
                ('is_out_of_business', models.BooleanField(verbose_name='Is out of business?')),
                ('year_started', models.PositiveIntegerField(verbose_name='Year started')),
                ('global_ultimate_duns_number', models.CharField(db_index=True, max_length=9, verbose_name='Glogal ultimate duns number')),
                ('employee_number', models.PositiveIntegerField(verbose_name='Employee number')),
                ('is_employees_number_estimated', models.BooleanField(verbose_name='Is employee number estimated?')),
                ('annual_sales', models.FloatField(help_text='Annual sales in US dollars', verbose_name='Annual sales')),
                ('is_annual_sales_estimated', models.BooleanField(verbose_name='Is annual sales estimated?')),
                ('legal_status', models.CharField(max_length=3, verbose_name='Legal status')),
                ('status_code', models.PositiveIntegerField(choices=[(0, 'Single location'), (1, 'Headquarter'), (2, 'Branch'), (4, 'Division')], verbose_name='Status code')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
