# Generated by Django 2.1.7 on 2019-04-01 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_updated_source', models.PositiveIntegerField(choices=[(1, 'File'), (2, 'API')])),
                ('duns_number', models.CharField(db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid', message='Field should contain 9 numbers only', regex='^\\d{9}$')])),
                ('business_name', models.CharField(max_length=90)),
                ('secondary_name', models.CharField(blank=True, max_length=90, null=True)),
                ('street_address', models.CharField(max_length=64)),
                ('street_address2', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country_name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=3)),
                ('postal_code', models.CharField(max_length=9)),
                ('national_id_number', models.CharField(max_length=16)),
                ('national_id_code_type', models.CharField(max_length=255)),
                ('line_of_business', models.CharField(max_length=41)),
                ('is_out_of_business', models.BooleanField()),
                ('year_started', models.PositiveIntegerField()),
                ('global_ultimate_duns_number', models.CharField(db_index=True, max_length=9)),
                ('employee_number', models.PositiveIntegerField()),
                ('is_employees_number_estimated', models.BooleanField()),
                ('annual_sales', models.FloatField(help_text='Annual sales in US dollars')),
                ('is_annual_sales_estimated', models.BooleanField()),
                ('legal_status', models.CharField(max_length=255)),
                ('status_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
