# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12.5
      - image: postgres:16
        environment:
          POSTGRES_DB: dnb-service
          POSTGRES_PASSWORD: dnb-service
      - image: cimg/redis:7.2.4

    working_directory: ~/repo

    environment:
      DATABASE_CREDENTIALS: '{"username": "postgres", "password": "dnbservice", "engine": "postgres", "port": 5432, "dbname": "dnb-service", "host": "localhost", "dbInstanceIdentifier": "db-instance"}'
      REDIS_URL: redis://localhost:6379

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test --cov-report xml --cov=.
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
