# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12.8
      - image: postgres:16
        environment:
          POSTGRES_DB: dnb-service
          POSTGRES_PASSWORD: dnb-service
      - image: cimg/redis:7.2.4

    working_directory: ~/repo

    environment:
      DATABASE_CREDENTIALS: '{"username": "postgres", "password": "dnb-service", "engine": "postgres", "port": 5432, "dbname": "dnb-service", "host": "localhost", "dbInstanceIdentifier": "db-instance"}'
      REDIS_URL: redis://localhost:6379

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Create and activate virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Run tests
          command: |
            python -m pytest --cov-report xml --cov=.
            python -m codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
