# Generated by Django 2.2.4 on 2019-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_updated_source',
        ),
        migrations.AddField(
            model_name='company',
            name='last_updated_source_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='monitoring_status',
            field=models.CharField(choices=[('not_enabled', 'Not enabled'), ('pending', 'Pending submission'), ('enabled', 'Enabled'), ('failed', 'Failed')], default='not_enabled', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='monitoring_status_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('unspecified', 'Unspecified'), ('corporation', 'Corporation'), ('joint_venture', 'Joint Venture'), ('partnership', 'Partnership'), ('proprietorship', 'Proprietorship'), ('government_body', 'Government Body'), ('cooperative', 'Cooperative'), ('non_profit_organisation', 'Non Profit Organization'), ('local_government_body', 'Local Government Body'), ('foreign_company', 'Foreign Company')], max_length=100, verbose_name='Legal status'),
        ),
    ]
