# Generated by Django 2.2.4 on 2019-11-20 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('company', '0003_auto_20191120_2228'), ('company', '0004_auto_20191120_2357')]

    dependencies = [
        ('company', '0002_auto_20191120_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=216, verbose_name='Website domain'),
        ),
        migrations.AddField(
            model_name='company',
            name='global_ultimate_primary_name',
            field=models.CharField(blank=True, max_length=90, verbose_name='Global ultimate Primary name'),
        ),
        migrations.AlterField(
            model_name='registrationnumber',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_numbers', to='company.Company'),
        ),
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=200)),
                ('priority', models.PositiveIntegerField()),
                ('typeDescription', models.CharField(max_length=200)),
                ('typeDnbCode', models.CharField(max_length=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_codes', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryIndustryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usSicV4', models.CharField(max_length=4)),
                ('usSicV4Description', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_industry_codes', to='company.Company')),
            ],
        ),
    ]
