# Generated by Django 2.2.4 on 2019-11-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191120_2228_squashed_0004_auto_20191120_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_sales_currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='Annual sales currency'),
        ),
    ]
