# Generated by Django 2.2.4 on 2019-11-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191120_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimaryIndustryCodes',
            new_name='PrimaryIndustryCode',
        ),
    ]
