# Generated by Django 2.2.4 on 2019-11-27 16:04

from django.db.models import JSONField
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('company', '0005_company_source'), ('company', '0006_auto_20191126_1536'), ('company', '0007_auto_20191126_1553')]

    dependencies = [
        ('company', '0004_company_annual_sales_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='source',
            field=JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_started',
            field=models.PositiveIntegerField(null=True, verbose_name='Year started'),
        ),
        migrations.RenameField(
            model_name='industrycode',
            old_name='typeDnbCode',
            new_name='typeDnBCode',
        ),
    ]
