# Generated by Django 2.2.4 on 2019-11-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_source_squashed_0007_auto_20191126_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrycode',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
