# Generated by Django 2.2.4 on 2019-11-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191127_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrycode',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
