# Generated by Django 2.2.4 on 2019-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20191127_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Employee number'),
        ),
    ]
