# Generated by Django 2.2.4 on 2019-12-02 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20191202_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='global_ultimate_duns_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid', message='Field should contain 9 numbers only', regex='^\\d{9}$')], verbose_name='Global ultimate Duns number'),
        ),
    ]
