# Generated by Django 2.2.4 on 2019-12-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20191202_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='global_ultimate_primary_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Global ultimate Primary name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_name',
            field=models.CharField(max_length=255, verbose_name='Primary name'),
        ),
    ]
