# Generated by Django 2.2.10 on 2020-03-09 12:48

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20191202_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duns_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Field should contain 9 numbers only', regex='^\\d{9}$')], verbose_name='Duns number')),
                ('changes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending submission'), ('submitted', 'Submitted')], default='pending', max_length=100, verbose_name='Change Request Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
