# Generated by Django 2.2.10 on 2020-03-10 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_changerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='duns_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid', message='Field should contain 9 numbers only', regex='^\\d{9}$')], verbose_name='Duns number'),
        ),
    ]
