# Generated by Django 2.2.10 on 2020-03-24 09:53

from django.db.models import JSONField
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200310_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_details', JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending submission'), ('submitted', 'Submitted')], db_index=True, default='pending', max_length=100, verbose_name='Investigation Request Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
