# Generated by Django 2.2.10 on 2020-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_investigationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending submission'), ('submitted', 'Submitted')], db_index=True, default='pending', max_length=100, verbose_name='Change Request Status'),
        ),
    ]
