# Generated by Django 2.2.10 on 2020-03-12 17:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20200325_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='worldbase_source_updated_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='worldbase_source',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
