# Generated by Django 2.2.10 on 2020-04-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200312_1720'),
        ('company', '0014_auto_20200325_1520'),
    ]

    operations = [
    ]
