# Generated by Django 2.2.10 on 2020-04-30 13:32

from django.db.models import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_merge_20200415_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='source',
            field=JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='worldbase_source',
            field=JSONField(blank=True, null=True),
        ),
    ]
