# Generated by Django 2.2.13 on 2020-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20200430_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
