# Generated by Django 2.2.20 on 2021-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210512_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_area_abbrev_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='State (Abbreviated)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address_area_abbrev_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='State (Abbreviated)'),
        ),
    ]
