# Generated by Django 2.2.28 on 2023-07-05 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20210729_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_duns_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Field should contain 9 numbers only', regex='^\\d{9}$')], verbose_name='Parent Duns number'),
        ),
    ]
