# Generated by Django 2.2.10 on 2020-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_squashed_0002_auto_20190417_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_enable_monitoring',
            field=models.BooleanField(default=False, help_text='Automatically register companies for live updates when queried via the API; NOTE: this option should only be enabled for data-hub.', verbose_name='auto enable monitoring'),
        ),
    ]
