# Generated by Django 2.2.4 on 2019-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dnb_direct_plus', '0001_initial'), ('dnb_direct_plus', '0002_auto_20191209_1402')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringFileRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('processed', models.PositiveIntegerField()),
                ('failed', models.PositiveIntegerField()),
            ],
        ),
    ]
