# Generated by Django 2.2.4 on 2019-12-09 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('dnb_direct_plus', '0002_monitoringfilerecord_timestamp'), ('dnb_direct_plus', '0003_auto_20191209_1850')]

    dependencies = [
        ('dnb_direct_plus', '0001_initial_squashed_0002_auto_20191209_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringfilerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 9, 15, 19, 46, 524079, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='monitoringfilerecord',
            old_name='processed',
            new_name='total',
        ),
    ]
